<?php $this->headTitle('Forgot Password'); ?>

<div class="mb-4 p-2">
    <h1 class="text-center"><a href="/">Forgot Your Password? That's Okay.</a></h1>
    <div class="grid gap-4 mt-8 border-2 bg-white border-slate-200 p-8 rounded-lg w-7/12 mx-auto">
        <?= $this->partial('app::message'); ?>
        <div class="py-2 px-4">
            <form id="linkedin-post-scheduler"
                  class="grid grid-cols-1 gap-2"
                  method="post"
                  action="/forgot-password">
                <div class="w-full">
                    <label for="email_address">Email Address:</label>
                    <input type="email"
                           name="email_address"
                           id="email_address"
                           placeholder="your email address">
                </div>
                <div class="w-full">
                    <input type="submit"
                           class="submit cursor-pointer"
                           name="submit"
                           value="Email me a password reset link">
                </div>
            </form>
        </div>
    </div>
</div>
