<?php $this->headTitle('Home'); ?>

<div class="mb-4 p-2">
    <h1><a href="/">LinkedIn Post Scheduler</a></h1>
    <p class="text-lg">
        With the LinkedIn Post Scheduler, you can schedule up to 50 LinkedIn posts to be published up to a month in advance.
    </p>
    <div class="grid grid-cols-3 gap-4 mt-4 border-t-2 border-slate-200 pt-4">
        <div class="col-span-2 pr-4 border-r-2 border-slate-200">
            <h2>Scheduled a New Post</h2>
            <form id="linkedin-post-scheduler"
                  class="grid grid-cols-1 gap-2"
                  method="post"
                  action="/posts">
                <div class="w-full">
                    <label>Title:</label>
                    <input type="text"
                           name="post_title" value="<?= $this->current_record->title ?? '' ?>">
                </div>
                <div class="w-full">
                    <label>Body:</label>
                    <textarea name="post_body"
                              rows="10"><?= $this->current_record->body ?? '' ?></textarea>
                </div>

                <div class="w-full">
                    <label>Publish On:</label>
                    <input type="datetime-local"
                           name="post_publish_date"
                           value="<?= $this->current_record->publish_on ?? '' ?>">
                </div>

                <div class="w-full">
                    <input type="hidden" name="id" value="<?= $this->current_record->id ?? '' ?>">
                    <input type="submit"
                           class="submit cursor-pointer"
                           name="submit"
                           value="<?= $this->current_record ? 'Update' : 'Schedule' ?> Post">
                </div>
            </form>
        </div>
        <div class="col-span-1">
            <h2 class="mb-1">Scheduled Posts</h2>
            <div class="text-sm text-slate-600 mb-4 mt-0">Click a post to edit it.</div>
            <?php foreach ($this->scheduled_posts as $postDate => $posts): ?>
                <div class="font-bold text-lg"><?= $postDate ?></div>
                <ul class="pl-4 ml-2 border-l-2 border-slate-100">
                <?php foreach ($posts as $post): ?>
                    <li><a href="/<?= $post->id; ?>"
                           class="<?= (
                                   $this->current_record &&
                                   $this->current_record->id === $post->id
                           )
                               ? 'active'
                               : '' ?>"
                        ><?= $post->title; ?></a></li>
                <?php endforeach;?>
                </ul>
            <?php endforeach;?>
        </div>
    </div>
</div>
