<?php $this->headTitle('Forgot Password'); ?>

<div class="mb-4 p-2">
    <h1 class="text-center"><a href="/">Reset Your Password</a></h1>
    <?php $this->partial('app::message'); ?>
    <div class="grid gap-4 mt-8 border-2 bg-white border-slate-200 p-8 rounded-lg w-4/5 w-auto">
        <div>
            <form id="linkedin-post-scheduler"
                  class="grid grid-cols-1 gap-2"
                  method="post"
                  action="/reset-password/<?= $this->reset_id; ?>">
                <div class="w-full">
                    <label>Password:</label>
                    <input type="password" name="password">
                </div>
                <div class="w-full">
                    <label>Confirm Password</label>
                    <input type="password" name="confirm_password">
                </div>
                <div class="w-full">
                    <input type="hidden" name="reset_id" value="<?= $this->reset_id; ?>">
                    <input type="submit"
                           class="submit cursor-pointer"
                           name="submit"
                           value="Reset My Password">
                </div>
            </form>
        </div>
    </div>
</div>
