services:

  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      target: core
      args:
        ENV: development
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/config/ini/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/config/ini/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini