<?php
$this->headLink()
    ->prependStylesheet('/css/styles.css');
$this->inlineScript();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <?=$this->headTitle('LinkedIn Post Scheduler')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>
<body>
    <div class="app-content">
        <main class="container">
            <?=$this->content?>
        </main>
    </div>

    <footer class="app-footer text-center">
        <div class="container">
            <hr />
            <p>
                &copy; <?=date('Y')?> <a href="https://matthewsetter.com">Matthew Setter</a>.
                All rights reserved.
                <?php if ($this->authUser !== null): ?>
                    <a href="/logout">Logout</a> / <a href="/profile">Profile</a>
                <?php endif ?>
                <?php if ($this->authUser === null && $this->matchedRouteName !== 'user.login'): ?>
                    <a href="/login">Login</a>
                <?php endif ?>
                <?php if ($this->authUser === null && $this->matchedRouteName !== 'user.register'): ?>
                    / <a href="/register">Register</a>
                <?php endif ?>
                <?php if ($this->authUser === null && $this->matchedRouteName !== 'user.forgot-password'): ?>
                    / <a href="/forgot-password">Forgot Password?</a>
                <?php endif ?>
            </p>
        </div>
    </footer>

    <?=$this->inlineScript()?>
</body>
</html>