<?php $this->headTitle('Home'); ?>

<div class="mb-4 p-2">
    <h1 class="text-center"><a href="/">User Profile</a></h1>
    <?php $this->partial('app::message'); ?>
    <div class="grid gap-4 mt-8 border-2 bg-white border-slate-200 p-8 rounded-lg w-4/5 w-auto">
        <div>
            <div class="w-full border-2 rounded-lg border-slate-100 text-white p-8">
                <div class="w-4/5">
                    <div class="mb-4">
                        <img src="/images/icons/avatar-icon-generic.png">
                        <!-- Image Credit: https://duckduckgo.com/?q=generic+gravatar+logo&t=h_&iax=images&ia=images&iai=http%3A%2F%2Fgetdrawings.com%2Ffree-icon-bw%2Fgeneric-avatar-icon-3.png -->
                    </div>
                    <p class="mb-0 font-bold text-purple-800"><?= $this->user->getFirstName(); ?> <?= $this->user->getLastName(); ?></p>
                    <p class="mb-2 mt-0"><?= $this->user->getEmailAddress(); ?></p></div>
                <p class="mb-2 mt-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dignissim volutpat velit non posuere. Donec pulvinar, metus a facilisis congue, arcu ex egestas nisi, nec consectetur quam nisi vel purus. Ut vulputate ligula neque, eget varius turpis eleifend vel. Morbi elementum sem in sapien dignissim, ut convallis magna ullamcorper. Etiam vel enim nisi. Donec at aliquam nulla. Quisque cursus vulputate dignissim. Donec efficitur augue quam. Integer sit amet nulla ullamcorper, hendrerit neque vel, aliquam risus. Donec magna justo, blandit in sapien ac, commodo tempor ligula. Suspendisse mauris nisi, posuere non varius ac, cursus facilisis elit. Nullam lacinia sollicitudin leo vel mollis. Ut luctus, velit nec sollicitudin vestibulum, enim massa placerat ex, eget lacinia felis nisl non justo. Integer auctor auctor urna. Pellentesque mollis massa enim, in fermentum est varius pulvinar. Phasellus a massa luctus, scelerisque augue a, accumsan est. </p>
                <?php if (! $this->user->isIntegratedWithLinkedIn()): ?>
                <a href="/linkedin-integration" class="block text-center mt-4 py-4 bg-purple-800 hover:bg-purple-700 p-2 focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 focus:ring-offset-slate-50 text-white font-semibold px-4 rounded-lg w-full hover:ease-in ease-out transition duration-150 hover:drop-shadow-md">Integrate with LinkedIn</a>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>
